#!/bin/sh
# usage: git-rehost-ipfs <git-repo> [name]
# git-rehost-ipfs - rehost a git repo on ipfs

if [ "$#" -eq 0 ] || [ "$#" -gt 2 ]; then
	echo "usage: $0 <git-repo> [<name>]"
	echo "rehost <git-repo> on ipfs"
	exit 1
fi

name=$(basename "$1")
[ -n "$2" ] && name="$2"

dir=$(mktemp -d -t git-ipfs-rehost-XXXXXX)
tohost="$dir/tohost"
repo="$dir/tohost/$name"
echo "rehosting $1"
git clone --bare "$1" "$repo"

if ls "$repo/objects/pack/"*.pack 1> /dev/null 2>&1; then
	cd "$repo" && cp objects/pack/*.pack . && \
		git unpack-objects < ./*.pack && \
		rm ./*.pack
fi

cd "$repo" && git update-server-info

hash=$(ipfs add -q -r "$tohost" | tail -n1)
echo "done"
echo
echo "repo rehosted at http://gateway.ipfs.io/ipfs/$hash/$name"
echo "you can clone it with:"
echo 
echo "  git clone http://gateway.ipfs.io/ipfs/$hash/$name"
